fullnameOverride: "<+service.name>"

mongodb:
  uri: "mongodb://admin:harnessbankingdemo@mongo-replicaset-0.mongo-replicaset-svc.prod.svc.cluster.local:27017"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "metrics"
  prometheus.io/path: '/metrics'

port: "9216"

replicas: 1

resources:
  limits:
    cpu: 250m
    memory: 192Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceMonitor:
  enabled: false

extraArgs:
  - --collect-all
  - --mongodb.collstats-colls=banking.auth