apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.name}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if .Values.rewriteDisabled}}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- end}}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      {{- if .Values.rootPath}}
      - path: /{{.Values.virtualPath}}(/|$)(.*)
      {{- else }}
      - path: /{{.Values.virtualPath}}/(.*)
      {{- end}}
        pathType: Prefix
        backend:
          service:
            name: {{.Values.name}}
            port:
              number: {{.Values.servicePort}}
    {{- if .Values.defineHost}}
    host: {{.Values.defineHost}}
    {{- end}}