pipeline:
  name: MySQL Background Testing
  description: This is a simple Integration Stage Pipeline.
  identifier: Broken_Pipeline_MySQL_Required_updated
  projectIdentifier: yps_poc_proj
  orgIdentifier: Product_Engineering
  stages:
    - stage:
        identifier: build
        type: CI
        name: build
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Background
                  name: harnessmysql
                  identifier: harnessmysql
                  spec:
                    connectorRef: DKRhubpersonalyps
                    image: mysql:8.1.0
                    shell: Sh
                    command: cat /etc/hostname
                    envVariables:
                      MYSQL_DATABASE: legacy
                      MYSQL_ROOT_PASSWORD: my-secret-pw
                    portBindings:
                      "3306": "3306"
                    runAsUser: "0"
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |
                      sleep 60
                      #telnet localhost 3306
                      #service mysql start
                      #systemctl status mysql
                      #sleep 20
                      #systemctl status mysql
                      #sudo systemctl start mysql
                      # mysql -h localhost -P 3306 -D legacy
                      mysql -u root -h localhost -pmy-secret-pw -D legacy --execute="SELECT VERSION();"
                    privileged: true
                    runAsUser: "0"
        description: ""
  tags: {}
